#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

if notTest "$@"
then

    ./Allrun.pre

    runApplication foamFormatConvert

    restore0Dir

    mkdir -p constant/modeShapes

    if [ -n "${FEM_MODE_CSV:-}" ]
    then
        python3 ../../scripts/map_fem_mode_to_patches.py \
            --case . \
            --patch-regex 'propeller.*' \
            --fem "$FEM_MODE_CSV" \
            --out constant/modeShapes/propellerMode1_mapped.csv
    else
        python3 ../../scripts/map_fem_mode_to_patches.py \
            --case . \
            --patch-regex 'propeller.*' \
            --fem constant/modeShapes/femMode1_sample.csv \
            --out constant/modeShapes/propellerMode1_mapped.csv \
            --make-sample-fem \
            --origin '(0 0 0)' \
            --axis '(0 1 0)'
    fi

    runApplication decomposePar

    for proc in processor*
    do
        [ -d "$proc/constant" ] && cp -rf constant/modeShapes "$proc/constant/"
    done

    runParallel $(getApplication)

    runApplication reconstructPar

fi

#------------------------------------------------------------------------------
